site_name: Seqera Platform Showcase Demonstration Docs

theme:
  name: material
  logo: assets/logo.svg
  features:
    - content.tooltips
    - navigation.footer
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
    - content.tabs.link
    - content.code.copy
  font:
    text: Sans Serif

  palette:
    primary: dark purple
    accent: dark purple

repo_url: https://github.com/ejseqera/showcase #TODO

extra_css:
  - "style.css"

extra_javascript:
  - https://buttons.github.io/buttons.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Showcase Demonstration:
    - Why use Seqera Platform?: intro.md
    - Getting started: demo_overview.md
    - Add a Pipeline: add_a_pipeline.md
    - Add a Dataset: add_a_dataset.md
    - Launch Pipeline: launch_pipeline.md
    - Monitor a Run: monitor_run.md
    - Monitoring views: monitoring_views.md
    - View Run Details: run_details.md
    - Resume a Pipeline: resume_pipeline.md
    - Data Explorer: data_explorer.md
    - Data Studios: data_studios.md
    - Optimize your Pipeline: pipeline_optimization.md
    - Automation on Seqera Platform: automation.md